Nowy prowadzący
AzureCommunityPL/warsztaty-2021 pull request #23
Opened 2021-09-23 16:33 UTC by maciejgos

2021-09-24 07:04 UTC, aryll requested changes

2021-09-24 07:04 UTC, aryll commented on _data/speakers.yaml
> +  twitter: https://twitter.com/
wywalisz ogólny link to twittera?

2021-09-24 07:04 UTC, aryll commented on _data/speakers.yaml
> +  level: Poziom niedostępny
wpisałabym tutaj poziom podstawowy

2021-09-24 07:04 UTC, aryll commented on _data/speakers.yaml
> +  level: Poziom niedostępny
w level

2021-09-24 07:04 UTC, aryll commented on _data/speakers.yaml
> +  dates: Piątki 5.11, 12.1,1 19.11, 26.11
brakuje nam od niego godziny i daty są w innym formacie niż u reszty prowadzących

2021-09-24 08:56 UTC, maciejgos commented on _data/speakers.yaml
> +  dates: Piątki 5.11, 12.1,1 19.11, 26.11
Format daty zmieniłem, czekam na potwierdzenie godziny

2021-09-24 08:56 UTC, maciejgos commented on _data/speakers.yaml
> +  twitter: https://twitter.com/
wywalone

2021-09-24 08:56 UTC, maciejgos commented on _data/speakers.yaml
> +  level: Poziom niedostępny
dodane

2021-09-25 07:30 UTC, maciejgos commented on _data/speakers.yaml
> +  dates: Piątki 5.11, 12.1,1 19.11, 26.11
Mamy komplet

2021-09-25 08:21 UTC, aryll approved these changes

2021-09-25 08:21 UTC, merged